### ISSUE TITLE
Events: Timestamps

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#110]
- [x] Format the Events Timestamps 
- Format should be in 'time' away from start date. 
  - **1y away** (greater than 52 weeks)
  - **8w away** (less than 52 weeks but greater than 4 weeks)
  - **7d away** (less than 4 weeks but greater than 24 hours)
  - **5h away** (less than 24 hours but greater than 60 minutes )
  - **12m away** (less than 60 minutes but greater than 60 seconds)
  - **Now** (less than 60 seconds but greater than 0 seconds)
  - **Started** (greater than 1sec but less than 24 hours)
  - **Finished** (greater than 24 hours)
- [x] The Event titles need to be truncated to accommodate for the event timestamps

**Comment by LucasCoelho** [comment]
@joshrio 
for all other timestamp on the app we stop at weeks, here you asked for years. I didn't do it to reuse existing function and for consistency
It's up to you, I can write two different specific funcions
