### ISSUE TITLE
Search Bar Concept

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#119]
I'd like to know if this is possible (search bar at the bottom of the Screen) as opposed to having it in the headers. It's a pain that we have to reach to the header to search (this is a design flaw in all apps). Imagine if you had to reach to the top of a screen to leave a comment (3rd screen) it'd make no sense. So search shouldn't be an exception.

![screen shot 2015-11-25 at 11 31 27 am](https://cloud.githubusercontent.com/assets/12651511/11409183/f51df3c0-9372-11e5-83b6-271ee0ccd3c4.png)

**Comment by LucasCoelho** [comment]
@joshrio we can put it on the bottom too

**Comment by joshrio** [comment]
Apply the current concept to the Music, and Search pages. (Ignore comments page and the tabs in the music, it's just conceptual.)

- [ ] Music: Should have a 'Search by Artist or Song' as the help text. 
  - It also needs an 'x' to clear the text
- [ ] Search" Should have "Search Sceene" as the help text.
  - It also needs an 'x' to clear the text
- [ ] Use apples native search bar for search
  - We're just going to style this like a normal text input field, exactly like when you send a message on iMessage.
- [ ] Use apples native 


![screen shot 2015-11-25 at 11 31 27 am](https://cloud.githubusercontent.com/assets/12651511/11409183/f51df3c0-9372-11e5-83b6-271ee0ccd3c4.png)

**Comment by LucasCoelho** [comment]
@joshrio should location adapt for this concept too?

**Comment by joshrio** [comment]
Yes... You're talking about location in settings right?
