### ISSUE TITLE
Progress Upload 

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#13]
Implement Progress Upload

- [ ] There's two states. 
 - Uploading: Red icon let's a user cancel an upload.
 - Error: Green icon let's a user retry if there was an issue.

https://drive.google.com/drive/u/0/folders/0B4waQesrkhW7fmFfbHJCVjZqZTZzOTZzU2FuNkZkRGN4aEhfemFrZGQ1Vk9RTWpuVmxXeFk

**Comment by LucasCoelho** [comment]
@joshrio added to sprint https://github.com/sceene/scn-ios-v1/issues/89
