### ISSUE TITLE
Events Feeds

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#140]
## Fix Broken Feeds

  - [x] Movies 
  - [x] Stadium Sports 
  - [ ] Tech & Innovation (Showing very little)
   - Issue made for Steve
  - [ ] Health & Fitness (Titles are missing)
   - Issue made for Steve
  - [x] Concerts & Festivals
  - [x] Local Music

## Additional Requirements
- [ ] Enable Refresh Feed's in all categories and sub categories
- [x] Create API issues for any errors/issues/problems you notice while implementing the feeds.

**Comment by joshrio** [comment]
All event changes have been pushed live. This will break the events vertical.
I have added the new response object to all event response. (I hope)
Please test the event endpoints to see the new response.
Let me know if there are any problems. (FYI - There were a huge number of changes made. There will be errors.)

Here are a couple new endpoints.

Concert:
http://api.sceene.com:5000/v1/event/music?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&subCat=concert&city=san%20francisco&region=CA&results=28

http://api.sceene.com:5000/v1/event/music?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&subCat=concert&genre=rock&city=san%20francisco&region=CA&results=15
http://api.sceene.com:5000/v1/event/music?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&subCat=concert&genre=rock&region=CA&results=28
&subCat=concert
&subCat=concert&genre=rock

Genre that work with concert
electronic
classic-rock
country
hip-hop
indie
jazz
pop
rap
rnb
rock

Music:Artist
http://api.sceene.com:5000/v1/music/artist?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&name=skrillex&keyword=events
http://api.sceene.com:5000/v1/music/artist?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&name=skrillex&keyword=videos
http://api.sceene.com:5000/v1/music/artist?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&name=skrillex&keyword=bio
http://api.sceene.com:5000/v1/music/artist?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&name=skrillex&keyword=songs

http://api.sceene.com:5000/v1/music/artist?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&UUID=en:ARZGBOU131FEA9FF8D (artist details)

Please let me know if you find anything that doesn't work. There were hundreds of changes so there will be some errors.

**Comment by LucasCoelho** [comment]
@joshrio 
 Tech & Innovation (Showing very little) - API - Not even sure it's a problem
 Health & Fitness (Titles are missing) - Issue was created on API repo
 Local Music - Not all genres are giving results. We should maybe rework its subcategories
