### ISSUE TITLE
Errors & Crashes

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#141]
## Required

- [x] Parse Settings Response Object
  - Reference: https://github.com/sceene/sprint-planning/issues/130
- [x] Card landing page UI
  - Reference: https://github.com/sceene/sprint-planning/issues/125
- [x] Cards are reloading when a user scrolls back up a feed
  - Reference: https://github.com/sceene/sprint-planning/issues/126

## Not Required
Aspect Ratios are not working and are buggy from all Sceene uploaded images. The solution, has been narrowed down to upgrading our version of img.ly
  - Reference: https://github.com/sceene/sprint-planning/issues/127
  - Reference: https://github.com/sceene/sprint-planning/issues/124
  - **Solution:** https://github.com/sceene/sprint-planning/issues/133

**Comment by LucasCoelho** [comment]
@joshrio This is probably caused because I was setting the cache time for images at 120 sec.
Changed it to 360 sec, let me know if it should still be longer and if it's ok you can close this issue
