### ISSUE TITLE
Activity Tab Bar Bug

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#147]
- [ ] Status bar activity tab error. 
  - Activity tab with maps, or call status enabled.
  - Previously marked as completed: https://github.com/sceene/sprint-planning/issues/101

**Comment by LucasCoelho** [comment]
@joshrio  _Alerts Landing Navigation
Should the alert type not the alert description
Example: Brunch not Brunch suggestions_
We don't have that info. `type` is places, `title` is Brunch suggestions
