### ISSUE TITLE
3. Update User Avatar, Background, Bio

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#151]
#### Overview

I've copy/pasted issues from the Pending API issue and made individual issues – like this one – with the original list and then the updated comment from Steve. 

**Please read**: Always check #github or #issues for Steves comments if my copy/pasted comment doesn't make sense. Always test, and make additional issues for Steve if data is missing.  

#### Issues

- [x] Profile Avatars Not Updating
  - Planning Reference: https://github.com/sceene/sprint-planning/issues/117
  - API Reference: https://github.com/sceene/scn-api-v1/issues/106

#### Github

**Please read carefully. I am moving away from using the "thing" endpoint. These endpoints should be used for person data and changing avatar, background and bio. These endpoints ensure the proper update of these data points.  Using legacy endpoints will NOT update cached data.**

Retrieve user info [including avatar and background]
http://api.sceene.com/v1/person/12028621040350873762?key=d1POQ8I2TVRVRLJOwMUdOl3iWPpOMOVEzkOZhHgQ&payload=

&payload=gallery [all images uploaded by user]
&payload=basic (use this to compare cache to stored values [me vs data])
&payload=detail

Create New Avatar
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: multipart/form-data" -H "Accept: application/json" -F "UUID=12028621040350873762" -F "fileUse=avatar" -F "file=@C:\Users\steve\Desktop\10a6f05.jpg" "http://api.sceene.com/v1/home/image?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

Create New Background
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: multipart/form-data" -H "Accept: application/json" -F "UUID=12028621040350873762" -F "fileUse=background" -F "file=@C:\Users\steve\Desktop\10a6f05.jpg" "http://api.sceene.com/v1/home/image?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

Create New Bio
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: application/json" -X PUT -d "{\"UUID\": \"12028621040350873762\",\"personBio\": \"test test1\"}" "http://api.sceene.com/v1/home/settings?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

#### Github

This should not be an issue if the correct endpoint is used to update the bio.

Couple things:
1)  The login bio response comes from cache.
2)  The correct endpoint for bio update (including cache) is = http://api.sceene.com/v1/home/settings
3) The param = personBio
4) The http method = PUT

Curl Example:
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: application/json" -X PUT -d "{\"UUID\": \"12028621040350873762\",\"personBio\": \"test test2\"}" "http://api.sceene.com/v1/home/settings?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

To ensure we have changed the cache and the main database, use basic person info endpoint.
http://api.sceene.com/v1/person/12028621040350873762?key=d1POQ8I2TVRVRLJOwMUdOl3iWPpOMOVEzkOZhHgQ&payload=basic

**Comment by LucasCoelho** [comment]
avatar and background are working
Bio is waiting on the API
