### ISSUE TITLE
1. Personalization | Menu | Current Settings 

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#153]
#### Final Feedback

Overall this is really looking good. Just a few minor adjustments. 

- [x] Add new segment controller active tabs and counter container
  - http://bit.ly/1lYeAY1
- [x] Align the Personalization and Current Settings title *and* subtitle with the Main Menu title and subtitle
 - [x] Move 10 px's up. 
 - [x] The tags section should move up with it too
- [x] Progress Bar 
 - [x] Make borders a hairline 
 - [x] Border color: rub: 187, 191, 196 (same as segment controller)
 - [x] Make the filler element the size of the progress bar so it looks like the *new* style.
  - See image below. 
- [x] Close should be "Close Menu"
- [x] Adding more than 10 settings crashes app. 

#### Question 

When removing a tag can we have 'removal' messages that's displayed. 
- [x] **Answer**: Yes we can. Check on the new build

11 settings +: Goodbye!, K, bai, thx. 
10 settings.  Banished to the ether!
9 settings.  Another one bites the dust.
8 settings. Pow, bang, zap. Gone. 
7 settings. Yeah, I don't like that either. 
6 settings. Good riddance.
5 settings. You are the removealist. 
4 settings. Delete, deplete, repeat. 
3 settings. Cya, wouldn't want to be yah.
2 settings. Getting low, low, low.
1 settings. You have to be odd to be number one.
0 settings. Back at square one. 😟

**Comment by joshrio** [comment]
![screen shot 2015-12-02 at 2 09 52 pm](https://cloud.githubusercontent.com/assets/12651511/11545839/68c4884e-98fe-11e5-8977-1e05defd24df.png)

**Comment by joshrio** [comment]
![screen shot 2015-12-02 at 2 14 31 pm](https://cloud.githubusercontent.com/assets/12651511/11545986/64a19440-98ff-11e5-96e1-6f4aa4b968a1.png)

**Comment by LucasCoelho** [comment]
@joshrio concerning the following
a) Border color: rub: 187, 191, 196 (same as segment controller)
b) Make the filler element the size of the progress bar so it looks like the new style.
See image below.

b) we can't really do it. To achieve it we can actually make it white with an alpha. Check the new build to see how it looks

**Comment by joshrio** [comment]
I have updated the drive links and posted in slack the assets needed. @LucasCoelho
