### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#157]
#### Overview

I've copy/pasted issues from the Pending API issue and made individual issues – like this one – with the original list and then the updated comment from Steve. 

**Please read**: Always check #github or #issues for Steves comments if my copy/pasted comment doesn't make sense. Always test, and make additional issues for Steve if data is missing.  

#### Reference

- [x] Bookmarking Showing Wrong order
  - Planning Reference: https://github.com/sceene/sprint-planning/issues/85
  - API Reference:  https://github.com/sceene/scn-api-v1/issues/105

#### Github

See Steve's comment
 - Reference: https://github.com/sceene/scn-api-v1/issues/105

**Comment by LucasCoelho** [comment]
Like steve wisely said: This has been corrected
