### ISSUE TITLE
Technology & Innovation Feed

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#159]
#### Overview

I've copy/pasted issues from the Pending API issue and made individual issues – like this one – with the original list and then the updated comment from Steve. 

**Please read**: Always check #github or #issues for Steves comments if my copy/pasted comment doesn't make sense. Always test, and make additional issues for Steve if data is missing.  

#### Issues

- [x] Category should be Tech & Innovation *not* Tech Innovation
- [x] Is Tech & Innovation Missing a lot of data or is it just not connected?
- [x] Tech & Innovation (Showing very little)
  - Reference: #140

#### Github

The technology (game) endpoint / query has been updated. It now includes Meet-Up data.

http://api.sceene.com/v1/event/technology?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&city=San%20Francisco&region=CA&results=50&keyword=gaming&page=1

In the event of a reduced number of responses for a specific keyword, remove city and just use region.

http://api.sceene.com/v1/event/technology?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&region=CA&results=50&keyword=gaming&page=1

**Comment by LucasCoelho** [comment]
@joshrio it seems like _Tech & Innovation (Showing very little)_ has been corrected by steve
