### ISSUE TITLE
1. Places Profile Page

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#163]
## API Documentation

https://sceene.slack.com/files/steve/F0FUBG7FT/menu_related_places_notes.txt

## Places Landing Page

Profile relates to the individual cards in the profile page, and the landing page is where all the 'more' content is. 

- [ ] Gallery
  - Landing: Display all images 
  - Profile: 9 images in container but degrade in 3's if 9 isn't available i.e. 9, 6, 3.
  - Endpoint: ``` "placeImages" ```

- [ ] Menus (if available)
  - Landing: All menus separated by menu type i.e Dinner, Desert. 
  - Profile: A social menu (two/three items from a menu)
  - Endpoint:``` "placeMenuSocial" ```

- [ ] Nearby
  - Landing: N/A
  - Profile: Five cards in the page and they should link to their profile page
  - ``` "placesNearby" ```

- [ ] About
  - Landing: Location Card, Hours, Contact, Additional Information
  - Profile: Location Card

- [ ] Reviews
  - Landing: Split into 3 individual sets
  - Profile: N/A

**Comment by LucasCoelho** [comment]
@joshrio are we gonna add "Block user" to an event action sheet?

**Comment by joshrio** [comment]
Yes

**Comment by joshrio** [comment]
What other information are you waiting on? @LucasCoelho

**Comment by joshrio** [comment]
Places Menu and Nearby Places update.

Menus are now showing up in profile pages where they are available. Nearby Places are showing up in profile pages where they are available.  These are complex queries that may still be a bit buggy. Please paste query url with any issue you create.

NOTE: Please do not create issues about insufficient data like missing menus.  Enhancing queries and adding more data sources needs to be discussed in meetings as an enhancement.

Please read the notes attached for a detailed example:
