### ISSUE TITLE
Comments Errors

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#164]
## Overview

**Please test things properly before making as completed.**

## Original Issue 

Link: https://github.com/sceene/sprint-planning/issues/158

## Issues

**iOS for sure**:
- [x] Avatars missing when posting a comment 
- [ ] Comments are posting twice as two different users with two different avatars
- [ ] Retry message should only appear if the message failed to send.
- [x] Divider lines don't hit the right screen bound.
- [x] Don't show the similar slide card once the user makes a comment. 

**Lucas thinks it's iOS but is not sure**:
- [ ] Timestamps are out of order and duplicating 
- [ ] Delete is deleting the wrong comments. 

**Lucas thinks it could be either iOS or API, gotta check**:
- [ ] When posting a comment I get an instant red error, and the comment doesnt post. 
- [x] Timeout error when posting comments
- [ ] Is there a time limit on the comments being posted, i.e can't post every second?

**Comment by joshrio** [comment]
## When posting a comment sometimes I get an instant red error, and the comment doesnt post.

![img_2554](https://cloud.githubusercontent.com/assets/12651511/11594034/a5d99508-9a5c-11e5-9e75-9fb457a14d9e.PNG)

**Comment by joshrio** [comment]
## Timeout error when posting comments

![img_2557](https://cloud.githubusercontent.com/assets/12651511/11594124/221ee3d4-9a5d-11e5-96ae-1fc516d89740.PNG)

**Comment by joshrio** [comment]
## Avatars missing when posting a comment 

![img_2558](https://cloud.githubusercontent.com/assets/12651511/11594125/225795da-9a5d-11e5-9b2e-1169fd6863f5.PNG)

**Comment by joshrio** [comment]
## Comments are posting twice as two different users with two different avatar

![img_2558](https://cloud.githubusercontent.com/assets/12651511/11594125/225795da-9a5d-11e5-9b2e-1169fd6863f5.PNG)

**Comment by joshrio** [comment]
## Timestamps are out of order and duplicating 

![img_2561](https://cloud.githubusercontent.com/assets/12651511/11594241/c011140e-9a5d-11e5-81b1-67f9d1b2628f.PNG)

**Comment by joshrio** [comment]
@LucasCoelho 

Comment Test is complete. 

Found a couple problems: 
1) Comment query results were being cached. Which would make it look like last comment wasn't being created. Then, after a few minutes, the new comment would just show up. FIXED
2) Comment Delete and Message Delete were mixing up their queries. In short, you couldn't delete comments and messages correctly. FIXED 
See attached doc for test queries. (will give insight into available get requests.)

steve = 12028621040350873762
josh = 11996664016025372834
music object = 12032106086672058530

[POST]
** create new comment
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: application/json" -X POST -d "{\"communicationSender\": \"12028621040350873762\",\"communicationMessage\": \"Test Comment 2\",\"communicationReceiver\": \"12032106086672058530\",\"object\": \"communication\"}" "http://api.sceene.com/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

comment UUID = 12106109029901093026 (add new uuid for new comment)

[GET]
** get all comments for communication object with id = 12032106086672058530 from user = 12028621040350873762
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ:  -D -X -H "Content-Type: application/json" "http://api.sceene.com:5000/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&communicationSender=12028621040350873762&UUID=12032106086672058530&object=communication"

** get all comments for communication object with id = 12032106086672058530
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ:  -D -X -H "Content-Type: application/json" "http://api.sceene.com:5000/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&UUID=12032106086672058530&object=communication"

** get all comments between sender and all communication objects
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ:  -D -X -H "Content-Type: application/json" "http://api.sceene.com:5000/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&communicationSender=12028621040350873762&object=communication"

** get all comments between sender and communication object with type = photo
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ:  -D -X -H "Content-Type: application/json" "http://api.sceene.com:5000/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&communicationSender=12028621040350873762&object=communication&communicationType=music"


[DELETE]
curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: application/json" -X DELETE -d "{\"communicationSender\": \"12028621040350873762\",\"UUID\": \"12106109029901093026\"}" "http://api.sceene.com:5000/v1/communication/comment?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

steve = 12028621040350873762
josh = 11996664016025372834

music = 12032106086672058530

**Comment by LucasCoelho** [comment]
waiting on https://github.com/sceene/scn-api-v1/issues/129
