### ISSUE TITLE
Global: Profile Actions 

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#169]
## Places Actions

- [x] Share
 - Trigger the Share Modal
- [x] Contact
 - Show real phone number. 
  - It's currently showing a hardcoded phone number. 
- [x] Uber
 - You can implement this without API. I'll need the following information (See image below)
  - REDIRECT URL
  - ORIGIN URI
- [x] Directions
 - Open in Apple maps

## Events Actions

- [x] Share
 - Trigger the Share Modal
- [ ] Get Tickets
  - ```  "eventTickets" ```
  - Translate the ``` provider ```: Ac = Active, Eb = Eventbrite, Tf = Ticketfly, Sg = Seatgeek etc
  - These should open a web view modal
- [ ] Uber
 - Same as Places UX
- [ ] Directions
 - Open in Apple maps

## People Actions

- [ ] Share
 - Trigger the Share Modal
- [ ] Contact 
  - Open the Conversation Screen Modal

**Comment by joshrio** [comment]
Required Information

![screen shot 2015-12-06 at 6 38 21 pm](https://cloud.githubusercontent.com/assets/12651511/11617852/baf6af64-9c48-11e5-872a-d969cf5c0aa6.png)

**Comment by joshrio** [comment]
Required Information

![screen shot 2015-12-06 at 6 38 21 pm](https://cloud.githubusercontent.com/assets/12651511/11617852/baf6af64-9c48-11e5-872a-d969cf5c0aa6.png)

**Comment by LucasCoelho** [comment]
concerning events:
 Get Tickets: "eventTickets" is nil for all event results
 Uber: API is not returning event's address
 Directions: API is not returning event's address

**Comment by LucasCoelho** [comment]
concerning People:
 Share people? I'll need more info, on how this will look
 Contact: it's already present on the right button icon

I'm not 100% sure we actually need an "Action" section on people because of the right nav icon

**Comment by LucasCoelho** [comment]
Concerning Uber:
What should we do if user has not the app?

**Comment by joshrio** [comment]
You should be passing the location of the event or place to Uber.

https://developer.uber.com/v1/endpoints/
