### ISSUE TITLE
Places: About

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#175]
## About Data

- [x] Implement the About 
Icons: [About Icons.zip](https://github.com/sceene/sprint-planning/files/55104/About.Icons.zip)

The cells should be 'responsive meaning if it doesn't fit in a half cell then the data should then show in the full length cell.

**Hours** 
Hours: ``` "placeHours" ```

**Contact Information**

Phone: ``` "placeContactPhone" ``` 
Facebook: ```  "placeFacebookID" ``` 
Twitter: ```  "placeTwitterScreenName" ``` 
Website: ``` "placeWebsite" ``` 

**Additional Information** 
Hours: ``` "placeExtended" ```

![screen shot 2015-12-03 at 4 27 56 pm](https://cloud.githubusercontent.com/assets/12651511/11578479/e4f35d00-99da-11e5-9346-9a4b2429d036.png)

**Comment by LucasCoelho** [comment]
@joshrio I'm guessing we should perform some kind of action when user clicks facebook/twitter/website? What exactly should be done?

**Comment by joshrio** [comment]
I think for now we don't worry about linking a user to a a site. However, when we do it, we'll do it by opening a web view within Sceene.

**Comment by joshrio** [comment]
@LucasCoelho 

I'm closing this and adding the remaining to a scrub.
