### ISSUE TITLE
Places Profile

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#177]
## Additional

There should be **NO** hardcoded data on these pages. Remove any and all elements that are hardcoded.

## API Documentation

https://sceene.slack.com/files/steve/F0FUBG7FT/menu_related_places_notes.txt

## Places Landing Page

Main relates to the main profile page. More relates to the more page where all the content is. Make sure the menu/navigation is updated and showing the following sections too.

http://api.sceene.com/v1/place/places?key=QQBx4jTpQK2CzadBK96hnqZXkfPxMvk4G7GM3kQvy&UUID=fs:49ca8f4df964a520b9581fe3

- [x] Gallery
  - More: Display all images 
  - Main: 9 images in container but degrade in 3's if 9 isn't available i.e. 9, 6, 3.
  - Endpoint: ``` "placeImages" ```

- [x] Menus (if available)
  - More: All menus separated by menu type i.e Dinner, Desert. 
  - Main: A social menu (two/three items from a menu)
  - Endpoint:``` "placeMenuSocial" ```

- [x] Nearby
  - More: N/A (This doesn't get a menu/navigation)
  - Main: Five cards in the page and they should link to their profile page
  - ``` "placesNearby" ```

- [x] About
  - More: Location Card, Hours, Contact, Additional Information
  - Main: Location Card
  - ``` "placeExtended" ```

- [x] Reviews
  - More: Split into 3 individual sets
  - Main: Show all reviews
  - ```"placeReviews" ```

## Github

Places Menu and Nearby Places update.

Menus are now showing up in profile pages where they are available. Nearby Places are showing up in profile pages where they are available.  These are complex queries that may still be a bit buggy. Please paste query url with any issue you create.

NOTE: Please do not create issues about insufficient data like missing menus.  Enhancing queries and adding more data sources needs to be discussed in meetings as an enhancement.

Please read the notes attached for a detailed example: https://sceene.slack.com/files/steve/F0FUBG7FT/menu_related_places_notes.txt

**Comment by LucasCoelho** [comment]
@joshrio I don't understand Reviews:
- More: Split into 3 individual sets - What sets? How should they be called? which reviews goes into which set?
- Main: Show all reviews - I don't think we want to display all reviews on the main page

**Comment by LucasCoelho** [comment]
@joshrio concerning Nearby places
What should we use as a description? Can you please ask steve to add whatever you choose to the nearby feeds?

**Comment by joshrio** [comment]
@LucasCoelho 

1. You can ignore the reviews part. It's fine the way it is. 
2. I don't think there is a description for the nearby. It's a light data card.

**Comment by LucasCoelho** [comment]
I read my comment and didn't understand it myself. I'll clarify:
We need the `description`, not for the nearby card itself but to the basic info card in case user presses the button to check the landing page. That's where the `description` is needed. 
This way we can avoid a blank page while info is loading (`description` is the only piece of info missing so we can have the same behavior as displaying landing pages from the feed)
