### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#178]
- [x] Uber only works on 5s. 
 - Have tried it on a 4s (iPad) and 6. 
 - I'm assuming this doesn't work on 6+ also.
- [x] Directions app linking to Google Maps or Apple Maps only works on 5s. 
 - Have tried it on a 4s (iPad) and 6. 
 - I'm assuming this doesn't work on 6+ also.
- [x] Directions action should be formatted as follows
  - Gray Label: Directions
  - Black Label: Apple Maps or Google Maps
- [x] The divider line on top of Places action directions should be the same length as the other actions. 
- [x] Put the same button press animation that's on the navigation icons on the buttons
  - Impossible to know if I have clicked on the button as a user.
- [x] Give the clicked state color: RGB: 245, 245, 235
  - The borders can stay the same color. 
- [x] I still need the following information for Uber API
  - REDIRECT URL
  - ORIGIN URI
- [x] Pass the location from the Sceene Profile to Uber Drop-off 
  - ``` dropoff[formatted_address]	string	URL-encoded address ``` or something like this.
  - See Uber documentation: https://developer.uber.com/v1/deep-linking/.
- [x] If the Uber app is installed, launch the Uber app; if the Uber app is not installed, launch Uber’s mobile site (m.uber.com).
  - See Uber documentation: https://developer.uber.com/v1/deep-linking/.

**Comment by LucasCoelho** [comment]
Uber + Maps: @joshrio while it might happen, it is rarely the case that something works on a device and not on another based on their model. What happens a lot is works in one iOS version and not on the other. Can you please tell me what iOS versions are installed on each device?

**Comment by LucasCoelho** [comment]
@joshrio 
- Redirect URL: https://sceene.com
- You don't need ORIGIN URI

**Comment by LucasCoelho** [comment]
@joshrio I only have a device on iOS 8, I'm the deeplinking bug happens only on iOS 9 + devices. I added some code which is needed on iOS 9. Can you test that on iOS 9 please and give me feedback?

**Comment by joshrio** [comment]
@LucasCoelho 

#1
1. iPad: iOS8
2. iPhone 5: iOS8
3. iPhone6: iOS9

#2
Thanks and that worked

#3. 
Can't test as profiles are crashing.
