### ISSUE TITLE
(Mon 14 - Fri 21)  Places Search

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#180]
- [ ]  Tie in Places Search

https://sceene.slack.com/files/steve/F0G3J6ZU2/apps_notes.txt

**Comment by LucasCoelho** [comment]
@joshrio should this somehow be integrated on the search tab bar?

**Comment by joshrio** [comment]
@LucasCoelho Yes.

**Comment by LucasCoelho** [comment]
@joshrio do ou wanna know what can be done with that or you want something specific to be developed?
