### ISSUE TITLE
Places: Profile Scrub

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#183]
- [ ] There's a weird flicker/animation/stutter in the Profile Bio/Background/Avatar section  
  - Reproduce: Transition from a feed card to a profile by clicking on the avatar.
- [x] Capitalize the Menu Titles on the More Menu Page
 - i.e. BREAKFAST not Breakfast
- [x] The 'More' button on the Location Card should link to the More About Page
- [x] On the More About page the map should maintain the same cell size as the main profile page. 
- [x] The location more button links to Menu. I should link to the about page.
- [ ] Add ```"rating"``` to the Profile Stats
- [x] The distance ```"miles"`` should be reflective of the true miles to a place. 
- [x] Let's put a button on the Nearby
  - See image
- [ ] Make the cell responsive so it can tolerate longer values in the cells. 
  - For example twitter links are being stack on top of each other
- [x] Change the men titles in the pull down menu 
  - Menus
  - Reviews
  - Gallery
  - About
- [ ] For the social links i.e. Facebook/Twitter show the screen name not the link
  - There is no web views that need to launch from these.
- [x] Don't show a Call Action, or Phone number cell on about if there's no number. 
- [ ] Fix the nearby crash. :)

**Comment by joshrio** [comment]
![screen shot 2015-12-09 at 2 28 38 pm](https://cloud.githubusercontent.com/assets/12651511/11700850/2c603dde-9e81-11e5-9e94-87c9dd6e7771.png)

**Comment by LucasCoelho** [comment]
@joshrio the crash on nearby will automagically get fixed when https://github.com/sceene/scn-api-v1/issues/122 gets fixed

**Comment by LucasCoelho** [comment]
@joshrio  Add "rating" to the Profile Stats
to fix this we'll need to change the places feed. We should discuss this today. Once we decide what should be on the description, we can ask steve to normalize the feed and display the same info on nearby (which contains the ratings but is missing the description) and on the places feeds (which is missing ratings but has a lot of non used info)

**Comment by LucasCoelho** [comment]
@joshrio what is a responsive cell?

**Comment by LucasCoelho** [comment]
@joshrio  _For the social links i.e. Facebook/Twitter show the screen name not the link_
Do you have an example with facebook so I can test? thanks

**Comment by joshrio** [comment]
@LucasCoelho 

Responsive cell: https://zpl.io/1xho0N
Current cell:

![img_2608](https://cloud.githubusercontent.com/assets/12651511/11719708/d84e72ca-9f10-11e5-972b-078e35a79aaa.PNG)

**Comment by joshrio** [comment]
Do you have an example with facebook so I can test?: "placeTwitterScreenName"

Already spoke to steve about adding that information to the feed, he likes the idea, I don't know if it'll be done now. In absence of that load the ratings on the second API call.

**Comment by joshrio** [comment]
Remaining issues were migrated too https://github.com/sceene/sprint-planning/issues/189
