### ISSUE TITLE
(Mon 14 - Fri 21) People Action Cards

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#184]
## People Actions

- [ ] Share
 - Trigger the Share Modal
- [ ] Contact 
  - Open the Conversation Screen Modal

Icons: [Message.zip](https://github.com/sceene/sprint-planning/files/66988/Message.zip)
UI
![people actions](https://cloud.githubusercontent.com/assets/12651511/11903787/6950486a-a570-11e5-979c-9c69a5521239.png)

**Comment by LucasCoelho** [comment]
@joshrio 
- where should I add these buttons?
- what should the share modal look like? "Sharing josh's profile"?
