### ISSUE TITLE
Places Profile & Feeds Issues

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#189]
## Feeds

- [x] Actions Sheets have various bugs.
  - People Menu shows up in Events Action sheet.
- [x] 502 Gateway Errors are popping up in a number of Places Cards

## Profiles

- [x] Flicker is still happening.
- [ ] Add the Rating in even if it's not available from the feed. 
- [ ] Theres an empty menu cell on the Menu Page
- [x] There's a weird flicker/animation/stutter in the Profile Bio/Background/Avatar section  
  - Reproduce: Transition from a feed card to a profile by clicking on the avatar.
- [ ] For the social links i.e. Facebook/Twitter show the screen name not the link
  - There is no web views that need to launch from these.
- [ ] Make the cell responsive so it can tolerate longer values in the cells. 
  - For example twitter links are being stack on top of each other
- [ ] Fix the nearby crash.
- [x] Add a loader to the Profile Page Navigation
  - Same one thats on the Feeds.

**Comment by joshrio** [comment]
# Action Sheet Bug

![img_2624](https://cloud.githubusercontent.com/assets/12651511/11753301/3972d594-9ff9-11e5-9e01-55d53668e46b.PNG)

**Comment by joshrio** [comment]
# 502 Error 

![img_2628](https://cloud.githubusercontent.com/assets/12651511/11753311/470b925e-9ff9-11e5-9c75-36e4e43adee6.PNG)

**Comment by joshrio** [comment]
## Empty Menu Cells

![img_2629](https://cloud.githubusercontent.com/assets/12651511/11753345/78ec736a-9ff9-11e5-90e3-669a281cabed.PNG)

**Comment by LucasCoelho** [comment]
@joshrio I spent almost 2 hours on this: _Actions Sheets have various bugs._ It's caused by my implementation of the infinite horizontal scrolling over a third party code. I'm moving on, and I'll get back to this later on. I'm thinking maybe taking care of this on the plane on wednesday

**Comment by LucasCoelho** [comment]
@joshrio can you explain me what you mean by _Flicker is still happening._?

**Comment by LucasCoelho** [comment]
_Add the Rating in even if it's not available from the feed._
What should be added if it's not available?

**Comment by LucasCoelho** [comment]
_Theres an empty menu cell on the Menu Page_
Can you give me the steps to reproduce this please?

**Comment by joshrio** [comment]
@LucasCoelho Flicker Issues


![flicker mov](https://cloud.githubusercontent.com/assets/12651511/11802449/9af3d486-a2a5-11e5-8c0c-9a635a1a7041.gif)

**Comment by joshrio** [comment]
@LucasCoelho 

Theres an empty menu cell on the Menu Page
Can you give me the steps to reproduce this please?

Go to Places ->  Restaurants ->  AQ Restaurant & Bar -> Menu (Feed or Nav). Result is below.

![img_2629](https://cloud.githubusercontent.com/assets/12651511/11753345/78ec736a-9ff9-11e5-90e3-669a281cabed.PNG)
