### ISSUE TITLE
Compose Post Screens

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#194]
Should all have the same layout as the share screen

**Comment by LucasCoelho** [comment]
@joshrio please develop more. I have no clue what is needed

**Comment by joshrio** [comment]
@LucasCoelho 

Sorry for the lack of information. Below is what I mean by making the compose post screens the same as the share screens. 

You'll see a preview label and a chevron. That doesn't need to be done now, but what will happen in the future is that it will let the user see what their post will look like before the post it.

![screen shot 2015-12-15 at 1 19 26 pm](https://cloud.githubusercontent.com/assets/12651511/11824457/82b73564-a32e-11e5-8c42-36e123ce1891.png)

**Comment by LucasCoelho** [comment]
@joshrio how would a share person look like?

**Comment by LucasCoelho** [comment]
@joshrio can you give me a screenshot of the preview page?
- What will we show at the right gray label ("1s")?
- Should we hide or disable the action buttons (share, like, more)?
- Should we hide or disable "Leave a comment" cell?

**Comment by joshrio** [comment]
Use the users avatar for the image. And the labels should say 

Sharing
(Username)

**Comment by joshrio** [comment]
1. Time stamp will say 'not posted'
2. Don't disable the interactions. If someone tries to click them a popup modal should say "Ooops

You can only do that once you've posted it"
3. Navigation header should say "preview"
4. Comments will be have like the interactions with the same modal

**Comment by joshrio** [comment]
![img_2998](https://cloud.githubusercontent.com/assets/12651511/11914936/bb6087d0-a644-11e5-9d7b-4024318fcea5.PNG)
