### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#34]
![inbox](https://cloud.githubusercontent.com/assets/12651511/10093408/e6a85f0c-6306-11e5-8bec-8ab50f9c10ba.png)
![conversation](https://cloud.githubusercontent.com/assets/12651511/10093409/e7ede6fc-6306-11e5-9796-f453efd3acb7.png)
![compose](https://cloud.githubusercontent.com/assets/12651511/10093410/ea2ee754-6306-11e5-82e1-4c59546b3dcc.png)

**Comment by joshrio** [comment]
SENDER

TEXT

Font: Helvetica Neue
Font Size: 14px
Line Height: 1.42 (20px)
Font Color: RGB: 255, 255, 255

BUBBLE

Border Radius: 16px
Color: RGB: 109, 207, 246
Bubble Margins: 16px left/right, 8px top/bottom

————————————————————————————

RECIEVER

TEXT

Font: Helvetica Neue
Font Size: 14px
Line Height: 1.42 (20px)
Font Color: RGB: 68, 68, 68

BUBBLE

Border Radius: 16px
Color: RGB: 215, 215, 215
Bubble Margins: 16px left/right, 8px top/bottom

————————————————————————————

BUBBLE SPACING


Max Width: 224px
Vertical Spacing: 4px

**Comment by joshrio** [comment]
Compose Measurements are the same as the inbox measurements except it's aligned 8px from the left.

**Comment by LucasCoelho** [comment]
@joshrio I noticed measurements are different from those of Followers list. Should I update Followers with those measurements too?

**Comment by joshrio** [comment]
@LucasCoelho Yes this is the list view template
