### ISSUE TITLE
Alerts Scrub

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#44]
### Parse ID’s

- [ ] Give steve the parse id’s so he can finish comments

### Alerts

- [ ] Give the left-swipe-action that's on comments
- [ ] The alerts and notifications are janky when scrolling
- [ ] Add the icons to the alert type
- https://drive.google.com/open?id=0B4waQesrkhW7aWVTNUhQanZBeVU
- [ ] Remove the remaining content image on the alerts panel (theres 9)
- [ ] Update the Alerts UI
![img_7399 2](https://cloud.githubusercontent.com/assets/12651511/10353061/89791ae0-6d08-11e5-8844-90b28946d1d5.PNG)

### Notifications 

- This should work exactly like instagram

- [ ] Show the users avatar on the left
- [ ] Show the content container on the right
- [ ] The content container on the right should link to the post
- [ ] The cell with the text shouldn’t be selectable
- [ ] The avatar should link to the users profile
- [ ] Give the left-swipe-action that's on comments
- [ ] Make sure the notifications can handle multi-line comments
- [ ] Usernames should be clickable and link to a profile

![notification](https://cloud.githubusercontent.com/assets/12651511/10372837/c9879648-6d9e-11e5-86b5-5f2bdcca4a86.png)

**Comment by LucasCoelho** [comment]
@joshrio  _The content container on the right should link to the post_
How about notifications with no image? On the notification side, is there gonna be a way to access my status card that's been liked by a friend?

**Comment by LucasCoelho** [comment]
Notification issues are in standby waiting for API development https://github.com/sceene/scn-api-v1/issues/45
