### ISSUE TITLE
Tab Bar

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#5]
Upgrade the current icons

- [ ] The list is below.

**Comment by joshrio** [comment]
- [ ] Implement the new line icons. 
 - Both active and inactive states have been provided 
 - http://bit.ly/1gVbJfV

![tab_3](https://cloud.githubusercontent.com/assets/12651511/9342602/a9b9ec04-45b1-11e5-87db-efc91810c879.png)

**Comment by LucasCoelho** [comment]
@joshrio let me know when you upload the active compose tab bar icon with correct sizes
