### ISSUE TITLE
3. HOME FEED

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#54]
## Home Feed

- [x] 1. Update Home Feed (Check with Steve this is latest, it should be)
http://api.sceene.com:5000/v1/home/feed?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&UUID=12010881061059250338
- [ ] 2. Make sure the avatars are being used and resized correctly via imgix
- [ ] 3. When posting a comment the user avatar isn't working  
- [ ] Is this being faked in the app, or not done through the API? If so, remove that improper comment posting process.
- [ ] 4. When liking the card it's blowing the header and comments section up.
- [ ] 5. We're going to go over the new home card layout separately. This will be it's own issue.

## 3. Comment Upload
![slack for ios upload png-5](https://cloud.githubusercontent.com/assets/12651511/10709405/d2875982-79e1-11e5-9fe1-46375cd8ffb0.jpeg)

## 5. Liking Issue
![img_1990](https://cloud.githubusercontent.com/assets/12651511/10709418/642513d4-79e2-11e5-8d23-c89b7cd48871.PNG)

**Comment by joshrio** [comment]
Rebuilt home feed response to match new schema and added bunch of missing items
@lucas:  Please test before I push it live cuz it will break your new release
http://api.sceene.com:5000/v1/home/feed?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&UUID=12010881061059250338

**Comment by lucas** [comment]
@joshrio pretty sure you're tagging the wrong person here
