### ISSUE TITLE
1. PROFILE

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#56]
## PROFILE LAYOUT

- [ ] Update the Profile Layout UI
 - http://bit.ly/1kOV3ss
 - **Tip: To see the measurements between two elements click an element then hover on another element.**

**Comment by joshrio** [comment]
@lucas copied from Github for you from Steve

"#57" Person Bio Update and Response has been changed.

Update a person bio endpoint:
       /v1/home/settings [PUT]

Payload:
    UUID
    personBio

Example:

curl -u eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ0MzYyOTk4OSwiZXhwIjoxNDUxNDA1OTg5fQ.eyJpZCI6bnVsbH0.w60e3wiZg-efKyJ8OBm0urYHAes97u3GZiP9ICVMdlQ: -H "Content-Type: application/json" -X PUT -d "{\"UUID\": \"12028621040350873762\",\"personBio\": \"Test Bio\"}" "http://api.sceene.com/v1/home/settings?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf"

Bio is now return as part of the people/person response object as "personBio".
It's also returned as part of (special use case) in other response objects, It's returned in the "me" var in the profile response:
http://api.sceene.com/v1/home/profile?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&UUID=12010881061059250338 and in the login response as "bio".

**Comment by lucas** [comment]
?

**Comment by joshrio** [comment]
"#58" is finished
https://github.com/sceene/scn-api-v1/issues/58

All requested data has been added to the profile response. Some of this data is redundant and is provided at login. However, is was duplicated here. The ability to follow someone has nothing to do with the profile response. Follow functionality (ability to follow someone) has been in place for quite some time.

Profile - Me variable has been added to the profile response: 
(the me variable will be added to other responses as required. however, the me variable data should not be needed as the same data is provided at login)

 "me": {
   "UUID": "12010881061059250338",
   "personBackgroundLink": "https://sceene-people.imgix.net/12072105691467696290.png (2MB)

",
   "personBio": "Quasi Aussie. Faux Real.",
   "followers": 8,
   "personCity": "",
   "personUserName": "josh",
   "following": 8,
   "personAvatarLink": "https://sceene-people.imgix.net/12078757273370314914.png (Not automatically expanded because 9MB is too large. You can expand it anyway or open it in a new window. ",
   "posts": 202
 }

**Comment by joshrio** [comment]
Zeppelin Documentation

zpl.io/ZuQEpp
