### ISSUE TITLE
Bookmark Bug

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#85]
- [ ] Bookmarks are bookmarking the wrong cards

![bookmark issue mov](https://cloud.githubusercontent.com/assets/12651511/11187347/e60c7828-8c3a-11e5-887d-6f8f7e6605b5.gif)

**Comment by LucasCoelho** [comment]
It is bookmarking the correct card, it's just not displaying it on top.
If you want this to happen ask steve (or ask me to as steve ;) ) to change the order on GET bookmarks

**Comment by joshrio** [comment]
@LucasCoelho I'll let you write the issue in Api for steve for this..
