### ISSUE TITLE
Activity 

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#88]
Zeplin: https://zpl.io/1WXCDg

- [x] Make the line height 4.1 
- [x] Make the Notification and Alert tab text no capital letters
- [x] Insert the vertical divider line
 - It's 36px high and a  hairline divider
- [ ] The alert icons are being resized to 32px. They should be 36px
- [ ] Insert the Alert badge 
 - It will slide the Notification text to the left when it's shown
- [x] Add Modes the the Activity action tab
 - Make the button link to the Mode page, just like the Notification and Alerts buttons do
- [x] When clicking the Activity icon in tab bar can we refresh the feed without the pull down menu showing?

**Comment by joshrio** [comment]
![activity](https://cloud.githubusercontent.com/assets/12651511/11232532/2d44f22c-8d69-11e5-960a-9a80c967df70.png)

**Comment by LucasCoelho** [comment]
@joshrio the images returned by API have a small transparent margin
check this image:
https://sceene.imgix.net/breakfastAlert.png?h=36&w=36&dpr=2

this is why The alert icons are being resized. You might wanna check with steve why this is happening

**Comment by joshrio** [comment]
I've made large icons that can be used. This way we'll just resize them via imigix instead!

![coffeealerticon](https://cloud.githubusercontent.com/assets/12651511/11376519/00d08d50-9296-11e5-87f5-5ee853fd93b3.png)
